---

- name: apply common envrionment configuration
  hosts: all
  roles:
  - common

- name: set up proxy server
  hosts: proxy
  roles:
  - swift-proxy

- name: set up storage server
  hosts: storage
  roles:
  - swift-storage