---
- name: restart ntp
  become: true
  service: name=ntp state=restarted
  tags: ntp

- name: apt clean
  become: true
  shell: apt-get clean

- name: apt update
  become: true
  apt: update_cache=yes
