---
# Configure NTP servers

- name: install ntp
  become: True
  apt: name=ntp state=present
  tags: ntp

- name: configure ntp file
  become: True
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp
  tags: ntp

- name: start the ntp service
  become: True
  service: name=ntp state=started enabled=yes
  tags: ntp
