# install pip and use aliyun's mirror
---

- name: copy get-pip.py
  copy: dest=~/get-pip.py src=get-pip.py

- name: check whether pip is already installed
  shell: which pip
  register: pip_path
  ignore_errors: true

- name: get pip
  become: true
  shell: python get-pip.py
  when: pip_path|failed

- name: copy pip.conf with aliyun's sources
  become: true
  copy: dest=/etc/pip.conf src=pip.conf
