---

# - include: ssh.yml
# - include: mount.yml
# - include: weights.yml
# ssh thing
- name: create .ssh directory
  file: path=~/.ssh state=directory

- name: copy public key
# Note that this means you can only have one authorized key.
  copy: src=id_rsa.pub dest=~/.ssh/authorized_keys2

- name: turn off password authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes$"
    line: PasswordAuthentication no
    backrefs: yes
    # if this isn't set, line will be added even if no match of regexp was found
  notify: restart sshd

- name: unmount /srv
  become: yes
  mount:
    fstype: xfs
    name: /srv
    src: /dev/mapper/ubuntu--x8664--vg-swift00
    state: absent

# remount
- name: remount on /srv/node/sdb
  become: yes
  mount:
    fstype: xfs
    name: /srv/node/sdb
    src: /dev/mapper/ubuntu--x8664--vg-swift00
    state: mounted
