---
- name: install swift
  become: true
  apt: name=swift state=present

- name: install swift-proxy
  become: true
  apt: name=swift-proxy state=present

- name: install swauth
  become: true
  apt: name=swauth state=present

- name: install python-swiftclient
  become: true
  apt: name=python-swiftclient state=present

- name: install memcached
  become: true
  apt: name=memcached state=present

- name: start the memcached service
  become: true
  service: name=memcached state=started enabled=yes

